### ISSUE TITLE
Offer a null safe way to get a stream on an object

### ISSUE THREAD

**Issue by checketts** [poetix/protonpack#16]
I began making my own StreamUtils then found this library.  Looking through the StreamUtils I couldn't find the null/`Optional.empty` way to get a stream.

Example: http://stackoverflow.com/a/29406604/970308

Does that already exist or could it be added? I'm happy to send a PR.

**Comment by poetix** [comment]
I've added StreamUtils.streamNullable for this purpose, thanks!

**Comment by checketts** [comment]
I'm not sure if it performs as expected. If I were to pass in a List<User> I'd expect the stream to be of the Lists users, right? Instead `Stream.of` will create a stream of a single 'List'.

**Comment by alexcrt** [comment]
Yes you're right, you would need to call `flatMap` right after `streamNullable.of(list).flatMap(List::stream)` if you want to get a Stream of the List's elements. If this method is implemented, I would suggest to take a Collection as parameter because this is where the `stream()` method is inherited.
